// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6lxR7JNjhVMRQAjp6Pq4lwRMeXoiwooY',
    appId: '1:1089712000439:android:0e07d252b30cda608fac32',
    messagingSenderId: '1089712000439',
    projectId: 'bigfish-chg',
    databaseURL: 'https://bigfish-chg-default-rtdb.firebaseio.com',
    storageBucket: 'bigfish-chg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbNp3PbLS9hbv-Hc_7C6JhBZ8XGoUeDcI',
    appId: '1:1089712000439:ios:86ca579f436059b08fac32',
    messagingSenderId: '1089712000439',
    projectId: 'bigfish-chg',
    databaseURL: 'https://bigfish-chg-default-rtdb.firebaseio.com',
    storageBucket: 'bigfish-chg.appspot.com',
    androidClientId: '1089712000439-veg83p7sdhncpsjq367b7t3jcgk0mtt1.apps.googleusercontent.com',
    iosClientId: '1089712000439-d2l65gnfudigk9fcl7h1jp06gpm0cu5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.fish1',
  );
}
